### PR TITLE
Add schematics

### PR DESCRIPTION
**Pull request by syssi**

### CODE REVIEW

**Comment by syssi** [comment]
@lucasimons I'm allowed to use your photo/sketch here? https://github.com/syssi/esphome-evse-wallbox/tree/add-schematics

**Comment by lucasimons** [comment]
Yes there are no problems ... I'm doing some tests but unfortunately they sent me the wrong contactor so I haven't tried seriously yet ...

**Comment by syssi** [comment]
Take your time and ping me if you made some progress / if you miss something.

**Comment by lucasimons** [comment]
I need a normally open contactor but they sent me a normally closed so when the evse start the charger, the coil is energised but  the contator is open so the car don't charge... I ordered a new one NO contator so when I will receive it,  I will be able to test all the settings or this component

**Pull request merged**
